# -*- coding: utf-8 -*-
"""decision_tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GPl0jmRAq9INavZWLS7jqurjEJ7AG_jh
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv("/content/heart.csv")

df.head()

df

df.info()

df.isnull().sum()

x=df.drop("target",axis=1)
y=df.target

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

x_train

from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)

from sklearn.tree import DecisionTreeClassifier  
model= DecisionTreeClassifier(criterion='gini', random_state=0)  
model.fit(x_train, y_train)

y_pred=model.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix

accuracy_score(y_test,y_pred)

confusion_matrix(y_test,y_pred)

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
plt.figure(figsize=(10,9), dpi=150)
plot_tree(model, feature_names=x.columns, filled=True);

